version: '3'
services:
  app:
    container_name: link-converter
    image: link-converter
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      DATASOURCE_HOST: postgres-db
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres